////------------------------------------------------------------------------------
//// <auto-generated>
////    This code was generated from a template.
////
////    Manual changes to this file may cause unexpected behavior in your application.
////    Manual changes to this file will be overwritten if the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace DailyShakespeare.DAL
//{
//    using System;
//    using System.Data.Entity;
//    using System.Data.Entity.Infrastructure;
    
//    public partial class DailyShakespeareContainer : DbContext
//    {
//        public DailyShakespeareContainer()
//            : base("name=DailyShakespeareContainer")
//        {
//        }
    
//        protected override void OnModelCreating(DbModelBuilder modelBuilder)
//        {
//            throw new UnintentionalCodeFirstException();
//        }
    
//        public DbSet<Monologue> Monologue { get; set; }
//        public DbSet<User> User { get; set; }
//        public DbSet<EmotionalState> EmotionalState { get; set; }
//        public DbSet<Play> Play { get; set; }
//        public DbSet<Character> Character { get; set; }
//        public DbSet<Gender> Gender { get; set; }
//        public DbSet<UserType> UserType { get; set; }
//    }
//}
