//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyShakespeare.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmotionalState
    {
        public EmotionalState()
        {
            this.Monologues = new HashSet<Monologue>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<Monologue> Monologues { get; set; }
    }
}
