//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyShakespeare.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Play
    {
        public Play()
        {
            this.Monologues = new HashSet<Monologue>();
            this.Characters = new HashSet<Character>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual ICollection<Monologue> Monologues { get; set; }
        public virtual ICollection<Character> Characters { get; set; }
    }
}
